### PR TITLE
Port US Presidential 2016 debate example to QI blog

### LINKED ISSUE #1: Port and update some entries from textasdata.com
Namely, this one https://github.com/textasdata/textasdata.github.io/issues/6

### PR DESCRIPTION
**Pull request by ciflikli**
This is just the scaffolding (regular text + updated code), however not yet knit with data - do you have the pdf? I tried replicating the procedure based on the supplementary [post](http://www.kenbenoit.net/how-to-batch-convert-pdf-files-to-text/) but don't think it works for me.

Closes #1

### CODE REVIEW

**Comment by stefan-mueller** [comment]
@ciflikli, I added the PDF file of the debate (still remembering the day when @kbenoit presented the blog post in one of my first text analysis classes). You should be able to read in the text with the **readtext** package, no need to use **pdftotext**.

Moreover, you could use `data_dictionary_RID` from the [**quanteda.dictionaries**](https://github.com/kbenoit/quanteda.dictionaries) package.

**Comment by ciflikli** [comment]
The file knits now; however the deploy preview shows a garbled text as abstract and the post itself gets a 404 - not sure why. @koheiw any ideas why this is the case? Locally it runs fine.

**Comment by koheiw** [comment]
If you want to include R code block, extension should be Rmarkdown.

**Comment by koheiw** [comment]
For blogdown, .Rmd and .Rmarkdown are different.
https://bookdown.org/yihui/blogdown/output-format.html

> In this book, we usually mean .Rmd files when we say “R Markdown documents,” which are compiled to .html by default. However, there is another type of R Markdown document with the filename extension .Rmarkdown. Such R Markdown documents are compiled to Markdown documents with the extension .markdown, which will be processed by Hugo instead of Pandoc. There are two major limitations of using .Rmarkdown compared to .Rmd:

**Pull request closed without merging**
