### PR TITLE
Quanteda v2

### PR DESCRIPTION
**Pull request by koheiw**
PR #25 did not work for some reason.. so issue a new PR.

### CODE REVIEW

**Comment by amatsuo** [comment]
I added tag-by-tag rss feeds. All posts with a particular tag will be included in the feed under `tags/tagname/index.xml`. 

For testing purposes, I put more tags to the posts. Once `master` is updated, the feed can be accessed from a URL like: `https://blog.quanteda.org/tags/r-bloggers/index.xml`.

**Comment by koheiw** [comment]
Currently, Github is responding really slowly....

**Comment by amatsuo** [comment]
seems so...

**Comment by kbenoit** [comment]
Awesome, thanks @amatsuo and @koheiw. 

On the r-bloggers and RSS feed, what's the sequence here? Are we good to merge and "publish" this or do we need to activate the RSS feed first, then register with R-bloggers, and then publish this?

If you know the answer, feel free to merge this PR and then do whatever needs to be done to publish it.

If you want me to register on R-bloggers, I can do that, or one of you can.

**Comment by koheiw** [comment]
Merged, so we are ready to send the RSS to R blogger. Who want to do this?
https://blog.quanteda.org/tags/r-bloggers/index.xml

**Comment by amatsuo** [comment]
> On the r-bloggers and RSS feed, what's the sequence here? Are we good to merge and "publish" this or do we need to activate the RSS feed first, then register with R-bloggers, and then publish this?

Just to answer this, when we update a master branch with a new article that has a tag `r-bloggers`, the RSS feed for this tag will be refreshed with the article.  The R-Bloggers website should be able to catch that and publish the new article there.

**Pull request merged**
